In [1]:
import pandas as pd
import numpy as np
import urllib

from bs4 import BeautifulSoup
from sklearn import tree
from sklearn.externals.six import StringIO

In [2]:
path = './ScoreCase/DecisionTree_sample.csv'
df = pd.read_csv(path,index_col=None,header=None,
                 names=['1H','2H','3H','4H','5H','6H','7H','8H','9H','10H','11H','12H',
                        '1A','2A','3A','4A','5A','6A','7A','8A','9A','10A','11A','12A',
                        'context'])

In [4]:
df

1H  2H  3H  4H  5H  6H  7H  8H  9H  10H   ...     4A  5A  6A  7A  8A  \
0      0   0   1   0   1   0   0   0   0    0   ...      0   2   0   0   0   
1      0   0   0   2   0   1   0   0   0    0   ...      0   0   0   0   0   
2      1   2   0   0   0   2   1   0   0    0   ...      1   0   0   0   2   
3      2   0   0   0   1   0   0   0   0    0   ...      0   0   0   1   3   
4      0   0   0   4   0   1   0   0   0    0   ...      0   0   0   0   0   
5      0   0   0   0   2   0   0   0   0    0   ...      3   0   0   0   0   
6      0   2   0   0   0   1   0   0   0    4   ...      0   1   0   2   0   
7      0   0   0   0   0   0   2   0   1    0   ...      3   3   3   0   3   
8      0   0   0   0   0   0   0   0   0    0   ...      0   0   1   0   3   
9      0   0   0   0   0   2   0   0   4    0   ...      0   3   0   2   4   
10     0   1   0   0   0   2   0   2   0    0   ...      0   0   0   0   0   
11     0   0   0   0   0   0   0   0   2    0   ...      1   0   0   0   0   
12     4   0   1   0   4   0   0   1   0    0   ...      2   1   0   0   0   
13     1   0   2   0   0   2   0   0   5    0   ...      0   1   0   0   0   
14     0   0   0   5   0   0   0   0   0    0   ...      0   0   0   1   2   
15     1   6   0   1   1   0   1   0   3    0   ...      1   1   2   1   1   
16     2   1   0   0   0   1   0   0   0    0   ...      0   2   0   4   8   
17     0   0   1   0   0   0   0   1   0    0   ...      0   0   6   0   2   
18     2   0   0   0   0   0   1   1   0    0   ...      0   0   1   0   0   
19     2   0   1   0   2   0   4   2   6    0   ...      0   0   0   3   0   
20     0   0   0   0   0   1   1   0   0    0   ...      0   2   0   0   0   
21     0   0   0   1   2   0   0   0   0    0   ...      0   0   0   1   0   
22     0   0   0   0   1   0   0   0   0    0   ...      1   0   1   1   0   
23     0   0   1   1   0   2   1   0   0    0   ...      1   0   0   0   1   
24     1   1   1   0   0   0   1   0   0    0   ...      0   0   3   0   0   
25     0   0   0   0   0   0   1   0   0    0   ...      0   0   1   0   1   
26     0   0   0   0   1   0   0   2   0    0   ...      0   0   0   0   0   
27     0   0   0   0   1   0   1   0   0    0   ...      0   0   0   1   0   
28     3   2   0   2   1   0   3   0   2    0   ...      0   0   0   0   2   
29     0   0   0   0   0   0   0   0   0    0   ...      0   0   0   0   0   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...     ..  ..  ..  ..  ..   
1314   0   0   0   1   0   1   1   0   0    0   ...      0   0   2   1   1   
1315   2   0   1   0   4   0   2   1   0    0   ...      0   0   1   1   0   
1316   0   0   0   0   2   0   0   0   0    0   ...      0   0   4   1   0   
1317   0   0   0   1   2   0   1   0   0    1   ...      0   0   0   1   0   
1318   0   0   0   0   0   1   0   1   0    0   ...      0   0   0   0   1   
1319   0   0   0   3   2   0   0   0   0    0   ...      1   0   0   0   0   
1320   0   0   0   0   0   0   0   0   0    0   ...      0   0   0   0   0   
1321   1   0   0   0   0   0   2   1   0    0   ...      0   0   1   0   0   
1322   4   0   1   1   0   0   0   0   1    0   ...      0   1   0   3   0   
1323   0   0   1   0   0   3   0   0   0    0   ...      0   0   0   0   0   
1324   0   2   0   2   0   3   1   1   0    0   ...      0   0   0   0   0   
1325   0   0   0   2   0   0   0   4   0    0   ...      0   1   1   0   0   
1326   0   0   0   2   2   0   0   0   0    0   ...      1   0   0   3   0   
1327   0   0   0   0   0   0   1   0   1    0   ...      0   0   0   0   1   
1328   0   0   0   1   0   0   1   0   0    0   ...      0   0   2   1   0   
1329   1   0   0   0   0   0   2   0   0    0   ...      0   3   0   0   0   
1330   0   0   0   0   0   1   1   0   1    1   ...      0   0   1   0   1   
1331   1   1   0   0   1   0   0   0   0    0   ...      0   0   0   0   0   
1332   0   0   1   1   1   0   2   0   0    0   ...      0   0   0   0   2   
1333   0   2   0   3   3   1

In [3]:
score = np.array(df.reindex(columns=['1H','2H','3H','4H','5H','6H','7H','8H','9H','10H','11H','12H',
                                     '1A','2A','3A','4A','5A','6A','7A','8A','9A','10A','11A','12A']))
                        
context = np.array(df.get('context'))
context_sen = [' ',
               '승리하였다.',
               '접전끝에 승리를 하였다.',
               '역전에 성공했다.',
               '완승을 하였다.',
               '무승부로 끝이났다.',
               '영봉승을 하였다.']

In [4]:
score

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 2, 0, ..., 0, 0, 0],
       ..., 
       [3, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 3, ..., 0, 0, 0]])

In [5]:
context

array([1, 1, 1, ..., 1, 3, 3])

In [6]:
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf = clf.fit(score,context)

In [7]:
clf.predict(np.array(score))

array([1, 1, 1, ..., 1, 3, 3])

1. 승리하였다.(패배하였다.
2. 접전끝에 승리를 하였다.(접전 끝에 패배를 하였다,진땀승을 거두었다.
3. 역전에 성공했다.(역전 당했다.
4. 완승을 하였다.(대승을 거뒀다,완패를 하였다.
5. 무승부로 끝이났다.
6. 영봉승을 하였다.

In [9]:
scoreBoard=[0,0,0,0,0,0,0,0,0,0,0,0,
           0,0,0,0,0,0,0,0,0,0,0,0,]

import random
cnt=5
for x in range(10):
    for y in range(cnt):
        scoreBoard[random.randint(0,8)]=random.randint(0,7)
        scoreBoard[random.randint(12,20)]=random.randint(0,7)
    for y in range(cnt):
        scoreBoard[random.randint(0,8)]=0
        scoreBoard[random.randint(12,20)]=0
    print scoreBoard[:12]
    print scoreBoard[12:25]
    print context_sen[clf.predict(np.array(scoreBoard))]

[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
역전에 성공했다.
[0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 2, 0, 5, 0, 0, 0, 0]
역전에 성공했다.
[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 6, 0, 0, 0, 0, 5, 0, 0, 0, 0]
역전에 성공했다.
[0, 0, 0, 6, 1, 0, 0, 0, 0, 0, 0, 0]
[3, 0, 0, 0, 0, 3, 0, 5, 0, 0, 0, 0]
승리하였다.
[0, 0, 0, 6, 0, 3, 0, 0, 0, 0, 0, 0]
[7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
승리하였다.
[0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0]
[7, 7, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0]
승리하였다.
[4, 0, 0, 0, 0, 6, 0, 6, 0, 0, 0, 0]
[3, 0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 0]
완승을 하였다.
[0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 0]
[0, 5, 5, 0, 0, 7, 0, 5, 0, 0, 0, 0]
완승을 하였다.
[0, 4, 0, 7, 0, 0, 2, 0, 3, 0, 0, 0]
[3, 5, 0, 0, 0, 7, 0, 6, 0, 0, 0, 0]
승리하였다.
[0, 0, 0, 0, 0, 0, 7, 0, 3, 0, 0, 0]
[3, 0, 4, 0, 0, 0, 5, 0, 0, 0, 0, 0]
완승을 하였다.


/home/gohyunyoung98/.local/lib/python2.7/site-packages/ipykernel/__main__.py:15: DeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future


In [31]:
print 15**24

16834112196028232574462890625
